export const REQUEST_TOKEN = 'REQUEST_TOKEN';
export const RECEIVE_TOKEN = 'RECEIVE_TOKEN';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT = 'LOGOUT';

export const REQUEST_BRANCHES = 'REQUEST_BRANCHES';
export const RECEIVE_BRANCHES = 'RECEIVE_BRANCHES';
export const REQUEST_PULL_REQUESTS = 'REQUEST_PULL_REQUESTS';
export const RECEIVE_PULL_REQUESTS = 'RECEIVE_PULL_REQUESTS';

export const CONVERT_PR = 'CONVERT_PR';
export const CONVERT_PR_DONE = 'CONVERT_PR_DONE';
export const CONVERT_PR_FAILED = 'CONVERT_PR_FAILED';
export const CONVERT_PR_CLEAR = 'CONVERT_PR_CLEAR';
